spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/psportclone
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: "polsatsportclone"
  main:
    web-application-type: servlet